In [20]:
import numpy as np
import pandas as pd                # Data exploration, manipulation functions
import matplotlib.pyplot as plt
import seaborn as sns 

In [21]:
pd.options.display.max_columns = 999

In [22]:
forest_train = pd.read_csv("train.csv") 

In [23]:
forest_train.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2596      51      3                               258   
1   2       2590      56      2                               212   
2   3       2804     139      9                               268   
3   4       2785     155     18                               242   
4   5       2595      45      2                               153   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                               0                              510   
1                              -6                              390   
2                              65                             3180   
3                             118                             3090   
4                              -1                              391   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0            221             232            148   
1            220             235            151   
2            234             238            135   
3            238             238            122   
4            220             234            150   

   Horizontal_Distance_To_Fire_Points  Wilderness_Area1  Wilderness_Area2  \
0                                6279                 1                 0   
1                                6225                 1                 0   
2                                6121                 1                 0   
3                                6211                 1                 0   
4                                6172                 1                 0   

   Wilderness_Area3  Wilderness_Area4  Soil_Type1  Soil_Type2  Soil_Type3  \
0                 0                 0           0           0           0   
1                 0                 0           0           0           0   
2                 0                 0           0           0           0   
3                 0                 0           0           0           0   
4                 0                 0           0           0           0   

   Soil_Type4  Soil_Type5  Soil_Type6  Soil_Type7  Soil_Type8  Soil_Type9  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   Soil_Type10  Soil_Type11  Soil_Type12  Soil_Type13  Soil_Type14  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            1            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type15  Soil_Type16  Soil_Type17  Soil_Type18  Soil_Type19  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type20  Soil_Type21  Soil_Type22  Soil_Type23  Soil_Type24  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type25  Soil_Type26  Soil_Type27  Soil_Type28  Soil_Type29  \
0            0            0            0            0            1   
1            0            0            0            0            1  

In [24]:
forest_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 56 columns):
Id                                    15120 non-null int64
Elevation                             15120 non-null int64
Aspect                                15120 non-null int64
Slope                                 15120 non-null int64
Horizontal_Distance_To_Hydrology      15120 non-null int64
Vertical_Distance_To_Hydrology        15120 non-null int64
Horizontal_Distance_To_Roadways       15120 non-null int64
Hillshade_9am                         15120 non-null int64
Hillshade_Noon                        15120 non-null int64
Hillshade_3pm                         15120 non-null int64
Horizontal_Distance_To_Fire_Points    15120 non-null int64
Wilderness_Area1                      15120 non-null int64
Wilderness_Area2                      15120 non-null int64
Wilderness_Area3                      15120 non-null int64
Wilderness_Area4                      15120 non-null int64
Soil_T

In [25]:
forest_train.shape

(15120, 56)

In [26]:
covertype_train = forest_train['Cover_Type']
data_train = forest_train.drop(['Id','Cover_Type'],axis = 1)

In [27]:
type(covertype_train)

pandas.core.series.Series

In [28]:
forest_test = pd.read_csv("test.csv")
data_test = forest_test.drop("Id",axis = 1)

In [29]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565892 entries, 0 to 565891
Data columns (total 54 columns):
Elevation                             565892 non-null int64
Aspect                                565892 non-null int64
Slope                                 565892 non-null int64
Horizontal_Distance_To_Hydrology      565892 non-null int64
Vertical_Distance_To_Hydrology        565892 non-null int64
Horizontal_Distance_To_Roadways       565892 non-null int64
Hillshade_9am                         565892 non-null int64
Hillshade_Noon                        565892 non-null int64
Hillshade_3pm                         565892 non-null int64
Horizontal_Distance_To_Fire_Points    565892 non-null int64
Wilderness_Area1                      565892 non-null int64
Wilderness_Area2                      565892 non-null int64
Wilderness_Area3                      565892 non-null int64
Wilderness_Area4                      565892 non-null int64
Soil_Type1                            565892 non-

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
sc = StandardScaler()

In [32]:
data_train = sc.fit_transform(data_train)
data_test = sc.transform(data_test)

In [33]:
import keras

In [34]:
from keras.models import Sequential
from keras.layers import Dense

In [13]:
classifier = Sequential()

In [97]:
classifier.add(Dense(units = 4,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54)) #First Hidden Layer

In [98]:
classifier.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'sigmoid')) # Output Layer. 8 units needed - 1 for each category and 1 extra as to_categorical creates an extra 0 class. Wont impact output as 0 is not present in training set at all

In [99]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [100]:
covertype_train

0        5
1        5
2        2
3        2
4        5
5        2
6        5
7        5
8        5
9        5
10       5
11       2
12       2
13       5
14       5
15       5
16       5
17       5
18       5
19       5
20       5
21       2
22       5
23       5
24       5
25       5
26       5
27       2
28       2
29       5
        ..
15090    3
15091    3
15092    3
15093    6
15094    6
15095    6
15096    6
15097    3
15098    3
15099    6
15100    3
15101    6
15102    3
15103    6
15104    3
15105    6
15106    3
15107    3
15108    3
15109    6
15110    6
15111    6
15112    6
15113    3
15114    3
15115    3
15116    3
15117    3
15118    3
15119    3
Name: Cover_Type, Length: 15120, dtype: int64

In [35]:
from keras.utils.np_utils import to_categorical

In [36]:
categorical_covertype_train = to_categorical(covertype_train)#`categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes)
categorical_covertype_train[0:10]

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

In [37]:
categorical_covertype_train.shape

(15120, 8)

In [38]:
categorical_covertype_train[0:100]

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 

In [89]:
#new_categorical_covertype_train = np.delete(categorical_covertype_train,0,axis=1)  # Dropping the extra column that got created. to_categorical converts int array from 0 to num_classes.Have to delete first column so put 0 and not 1
## Cannot use this approach as predict is predicting class 0 which doesnt exist and excluding class 7


In [90]:
#new_categorical_covertype_train[0:100]

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
 

In [104]:
classifier.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 200)

Epoch 1/200
15120/15120 [==============================] - 1s 38us/step - loss: 2.0776 - acc: 0.1913
Epoch 2/200
15120/15120 [==============================] - 0s 4us/step - loss: 2.0713 - acc: 0.2438
Epoch 3/200
15120/15120 [==============================] - 0s 5us/step - loss: 2.0610 - acc: 0.2405
Epoch 4/200
15120/15120 [==============================] - 0s 5us/step - loss: 2.0453 - acc: 0.2629
Epoch 5/200
15120/15120 [==============================] - 0s 5us/step - loss: 2.0238 - acc: 0.2817
Epoch 6/200
15120/15120 [==============================] - 0s 5us/step - loss: 1.9963 - acc: 0.3917
Epoch 7/200
15120/15120 [==============================] - 0s 6us/step - loss: 1.9638 - acc: 0.4167
Epoch 8/200
15120/15120 [==============================] - 0s 6us/step - loss: 1.9269 - acc: 0.4279
Epoch 9/200
15120/15120 [==============================] - 0s 6us/step - loss: 1.8867 - acc: 0.4412
Epoch 10/200
15120/15120 [==============================] - 0s 5us/step - loss: 1.8440 - acc: 0.446

In [105]:
pred_test = classifier.predict_classes(data_test)   # .predict gives probabilites and not classes

In [106]:
pred_test

array([5, 2, 2, ..., 3, 3, 3], dtype=int64)

In [107]:
forest_test['Cover_Type'] = pred_test   # The basic model with 1 hidden layer with 4 units and Training with 200 epochs gave a kaggle score of 0.53 
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

# Doubling the number of epochs

In [108]:
classifier.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7919 - acc: 0.6690
Epoch 2/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7910 - acc: 0.6692
Epoch 3/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7905 - acc: 0.6665
Epoch 4/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7899 - acc: 0.6678
Epoch 5/400
15120/15120 [==============================] - 0s 4us/step - loss: 0.7893 - acc: 0.6675
Epoch 6/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7887 - acc: 0.6682
Epoch 7/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7881 - acc: 0.6685
Epoch 8/400
15120/15120 [==============================] - 0s 5us/step - loss: 0.7874 - acc: 0.6679
Epoch 9/400
15120/15120 [==============================] - 0s 4us/step - loss: 0.7870 - acc: 0.6686
Epoch 10/400
15120/15120 [==============================] - 0s 4us/step - loss: 0.7864 - acc: 0.6711

In [110]:
pred_test = classifier.predict_classes(data_test)

In [111]:
forest_test['Cover_Type'] = pred_test   # The basic model with 1 hidden layer with 4 units and Training with 400 epochs gave a kaggle score of 0.54. Minor improvement 
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## Building an NN with softmax activation function instead of sigmoid. 

In [125]:
classifier2 = Sequential()

In [126]:
classifier2.add(Dense(units = 4,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#Input Layer

In [127]:
classifier2.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))

In [128]:
classifier2.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [117]:
categorical_covertype_train.shape

(15120, 8)

In [118]:
data_train.shape

(15120, 54)

In [129]:
classifier2.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 1s 47us/step - loss: 2.0745 - acc: 0.2280
Epoch 2/400
15120/15120 [==============================] - 0s 6us/step - loss: 2.0591 - acc: 0.2843
Epoch 3/400
15120/15120 [==============================] - 0s 6us/step - loss: 2.0328 - acc: 0.3048
Epoch 4/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.9914 - acc: 0.3201
Epoch 5/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.9342 - acc: 0.3194
Epoch 6/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.8647 - acc: 0.3134
Epoch 7/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.7889 - acc: 0.3308
Epoch 8/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.7126 - acc: 0.3481
Epoch 9/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.6400 - acc: 0.3687
Epoch 10/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.5734 - acc: 0.369

In [132]:
pred_test = classifier.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5,
       5, 5, 2, 5, 5, 5, 5, 2, 2, 2, 2, 2], dtype=int64)

In [133]:
forest_test['Cover_Type'] = pred_test   # The basic model with 1 hidden layer with 4 units and Training with 400 epochs with softmax gave a kaggle score of 0.5496. No difference in accuracy between using the 2 classifiers 
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## Building a NN with more neurons

In [18]:
classifier3 = Sequential()

In [19]:
classifier3.add(Dense(units = 25,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer

In [20]:
classifier3.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))

In [21]:
classifier3.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [22]:
classifier3.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 23us/step - loss: 2.0588 - acc: 0.3268
Epoch 2/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.9898 - acc: 0.4975
Epoch 3/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.8646 - acc: 0.5268
Epoch 4/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.6854 - acc: 0.5391
Epoch 5/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.4888 - acc: 0.5563
Epoch 6/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.3166 - acc: 0.5817
Epoch 7/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.1908 - acc: 0.5873
Epoch 8/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.1044 - acc: 0.6029
Epoch 9/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.0463 - acc: 0.6077
Epoch 10/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.0051 - acc: 0.614

In [23]:
pred_test = classifier3.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [24]:
forest_test['Cover_Type'] = pred_test   # The model with 25 neurons and 1 hidden layer gave huge improvement in Kaggle score from 0.54 to 0.64
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [26]:
classifier4 = Sequential()

In [27]:
classifier4.add(Dense(units = 40,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer

In [28]:
classifier4.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))

In [29]:
classifier4.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [30]:
classifier4.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 27us/step - loss: 2.0490 - acc: 0.3502
Epoch 2/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.9446 - acc: 0.5432
Epoch 3/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.7622 - acc: 0.5674
Epoch 4/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.5259 - acc: 0.5776
Epoch 5/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.3112 - acc: 0.5841
Epoch 6/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.1603 - acc: 0.5928
Epoch 7/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.0639 - acc: 0.6024
Epoch 8/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.0044 - acc: 0.6124
Epoch 9/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.9649 - acc: 0.6175
Epoch 10/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.9357 - acc: 0.626

In [31]:
pred_test = classifier4.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 5, 5, 5,
       5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [33]:
forest_test['Cover_Type'] = pred_test   # The model with 40 neurons and 1 hidden layer gave improvement in Kaggle score from 0.64 to 0.66
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [34]:
classifier5 = Sequential()

In [35]:
classifier5.add(Dense(units = 52,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer

In [36]:
classifier5.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))

In [37]:
classifier5.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [38]:
classifier5.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 26us/step - loss: 2.0453 - acc: 0.3774
Epoch 2/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.9208 - acc: 0.5438
Epoch 3/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.7055 - acc: 0.5741
Epoch 4/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.4421 - acc: 0.5845
Epoch 5/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.2236 - acc: 0.5876
Epoch 6/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.0818 - acc: 0.5997
Epoch 7/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.0009 - acc: 0.6069
Epoch 8/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.9519 - acc: 0.6161
Epoch 9/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.9199 - acc: 0.6278
Epoch 10/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.8957 - acc: 0.636

In [39]:
pred_test = classifier5.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5,
       5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [40]:
forest_test['Cover_Type'] = pred_test   # The model with 40 neurons and 1 hidden layer gave improvement in Kaggle score from 0.66 to 0.67
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [42]:
classifier6 = Sequential()
classifier6.add(Dense(units = 75,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 26us/step - loss: 2.0105 - acc: 0.4562
Epoch 2/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.8100 - acc: 0.5751
Epoch 3/400
15120/15120 [==============================] - 0s 6us/step - loss: 1.5217 - acc: 0.5822
Epoch 4/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.2591 - acc: 0.5956
Epoch 5/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.0871 - acc: 0.6056
Epoch 6/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.9889 - acc: 0.6138
Epoch 7/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.9340 - acc: 0.6258
Epoch 8/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.8998 - acc: 0.6352
Epoch 9/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.8751 - acc: 0.6460
Epoch 10/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.8566 - acc: 0.649

In [43]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 5, 5, 5,
       5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2], dtype=int64)

In [44]:
forest_test['Cover_Type'] = pred_test   # The model with 40 neurons and 1 hidden layer gave improvement in Kaggle score from 0.67 to 0.685
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [45]:
classifier6 = Sequential()
classifier6.add(Dense(units = 130,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 28us/step - loss: 1.9914 - acc: 0.4331
Epoch 2/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.7117 - acc: 0.5928
Epoch 3/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.3515 - acc: 0.6046
Epoch 4/400
15120/15120 [==============================] - 0s 7us/step - loss: 1.0849 - acc: 0.6105
Epoch 5/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.9582 - acc: 0.6306
Epoch 6/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.8992 - acc: 0.6426
Epoch 7/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.8636 - acc: 0.6517
Epoch 8/400
15120/15120 [==============================] - 0s 6us/step - loss: 0.8386 - acc: 0.6619
Epoch 9/400
15120/15120 [==============================] - 0s 7us/step - loss: 0.8187 - acc: 0.6694
Epoch 10/400
15120/15120 [==============================] - 0s 8us/step - loss: 0.8029 - acc: 0.671

In [46]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5,
       5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [47]:
forest_test['Cover_Type'] = pred_test   # The model with 40 neurons and 1 hidden layer gave improvement in Kaggle score from 0.68 to 0.70
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [48]:
classifier6 = Sequential()
classifier6.add(Dense(units = 300,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 0s 31us/step - loss: 1.8855 - acc: 0.4747
Epoch 2/400
15120/15120 [==============================] - 0s 10us/step - loss: 1.3903 - acc: 0.6054
Epoch 3/400
15120/15120 [==============================] - 0s 11us/step - loss: 1.0376 - acc: 0.6137
Epoch 4/400
15120/15120 [==============================] - 0s 10us/step - loss: 0.9118 - acc: 0.6324
Epoch 5/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.8594 - acc: 0.6477
Epoch 6/400
15120/15120 [==============================] - 0s 10us/step - loss: 0.8261 - acc: 0.6617
Epoch 7/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.8021 - acc: 0.6678
Epoch 8/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.7825 - acc: 0.6744
Epoch 9/400
15120/15120 [==============================] - 0s 10us/step - loss: 0.7656 - acc: 0.6857
Epoch 10/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.7504 - a

In [49]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 5, 5, 5,
       5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [50]:
forest_test['Cover_Type'] = pred_test   # The model with 40 neurons and 1 hidden layer gave improvement in Kaggle score from 0.70 to 0.72
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## Adding and additional hidden layer

In [51]:
classifier6 = Sequential()
classifier6.add(Dense(units = 300,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 10,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 1s 38us/step - loss: 2.0623 - acc: 0.3059
Epoch 2/400
15120/15120 [==============================] - 0s 10us/step - loss: 1.9525 - acc: 0.4236
Epoch 3/400
15120/15120 [==============================] - 0s 11us/step - loss: 1.6349 - acc: 0.4235
Epoch 4/400
15120/15120 [==============================] - 0s 10us/step - loss: 1.2391 - acc: 0.5147
Epoch 5/400
15120/15120 [==============================] - 0s 11us/step - loss: 1.0336 - acc: 0.5842
Epoch 6/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.9466 - acc: 0.5958
Epoch 7/400
15120/15120 [==============================] - 0s 10us/step - loss: 0.9025 - acc: 0.6098
Epoch 8/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.8724 - acc: 0.6231
Epoch 9/400
15120/15120 [==============================] - 0s 10us/step - loss: 0.8453 - acc: 0.6403
Epoch 10/400
15120/15120 [==============================] - 0s 11us/step - loss: 0.8218 - a

In [52]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 5, 5, 5,
       5, 5, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2], dtype=int64)

In [53]:
forest_test['Cover_Type'] = pred_test   # The model with 2 hidden layer gave improvement in Kaggle score from 0.72 to 0.73
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 300,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 100,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 1s 42us/step - loss: 1.9885 - acc: 0.4295
Epoch 2/400
15120/15120 [==============================] - 0s 14us/step - loss: 1.4539 - acc: 0.5556
Epoch 3/400
15120/15120 [==============================] - 0s 13us/step - loss: 0.9811 - acc: 0.6112
Epoch 4/400
15120/15120 [==============================] - 0s 13us/step - loss: 0.8677 - acc: 0.6383
Epoch 5/400
15120/15120 [==============================] - 0s 14us/step - loss: 0.8132 - acc: 0.6579
Epoch 6/400
15120/15120 [==============================] - 0s 14us/step - loss: 0.7801 - acc: 0.6748
Epoch 7/400
15120/15120 [==============================] - 0s 14us/step - loss: 0.7505 - acc: 0.6875
Epoch 8/400
15120/15120 [==============================] - 0s 13us/step - loss: 0.7275 - acc: 0.6959
Epoch 9/400
15120/15120 [==============================] - 0s 14us/step - loss: 0.7027 - acc: 0.7058
Epoch 10/400
15120/15120 [==============================] - 0s 13us/step - loss: 0.6845 - a

In [55]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 5, 5, 5,
       5, 5, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2], dtype=int64)

In [56]:
forest_test['Cover_Type'] = pred_test   # The model with 2 hidden layer gave improvement in Kaggle score from 0.73 to 0.74
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 300,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 300,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 1s 53us/step - loss: 1.7940 - acc: 0.4792
Epoch 2/400
15120/15120 [==============================] - 0s 24us/step - loss: 1.0466 - acc: 0.6036
Epoch 3/400
15120/15120 [==============================] - 0s 23us/step - loss: 0.8527 - acc: 0.6439
Epoch 4/400
15120/15120 [==============================] - 0s 22us/step - loss: 0.7885 - acc: 0.6712
Epoch 5/400
15120/15120 [==============================] - 0s 22us/step - loss: 0.7470 - acc: 0.6879
Epoch 6/400
15120/15120 [==============================] - 0s 23us/step - loss: 0.7122 - acc: 0.7024
Epoch 7/400
15120/15120 [==============================] - 0s 22us/step - loss: 0.6837 - acc: 0.7147
Epoch 8/400
15120/15120 [==============================] - 0s 22us/step - loss: 0.6598 - acc: 0.7236
Epoch 9/400
15120/15120 [==============================] - 0s 22us/step - loss: 0.6442 - acc: 0.7292
Epoch 10/400
15120/15120 [==============================] - 0s 21us/step - loss: 0.6211 - a

In [58]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 1, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 5, 5, 5,
       5, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2], dtype=int64)

In [59]:
forest_test['Cover_Type'] = pred_test   # The model with 2 hidden layer gave improvement in Kaggle score from 0.74 to 0.7594
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## Finally kaggle test set accuracy reduced to 0.73 after addinfg 3rd hidden layer

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 400,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 400,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dense(units = 100,activation = 'relu',kernel_initializer = 'uniform')) #3rd hidden layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 400)

Epoch 1/400
15120/15120 [==============================] - 1s 72us/step - loss: 1.8607 - acc: 0.3873
Epoch 2/400
15120/15120 [==============================] - 1s 36us/step - loss: 1.0602 - acc: 0.5807
Epoch 3/400
15120/15120 [==============================] - 1s 36us/step - loss: 0.8524 - acc: 0.6384
Epoch 4/400
15120/15120 [==============================] - 1s 36us/step - loss: 0.7634 - acc: 0.6820
Epoch 5/400
15120/15120 [==============================] - 1s 36us/step - loss: 0.7183 - acc: 0.7001
Epoch 6/400
15120/15120 [==============================] - 1s 39us/step - loss: 0.6811 - acc: 0.7113
Epoch 7/400
15120/15120 [==============================] - 1s 57us/step - loss: 0.6505 - acc: 0.7276
Epoch 8/400
15120/15120 [==============================] - 1s 47us/step - loss: 0.6269 - acc: 0.7358
Epoch 9/400
15120/15120 [==============================] - 1s 35us/step - loss: 0.6114 - acc: 0.7358
Epoch 10/400
15120/15120 [==============================] - 1s 36us/step - loss: 0.5899 - a

In [61]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 5, 5, 5,
       5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [62]:
forest_test['Cover_Type'] = pred_test   # The model with 3 hidden layer reduced accuracy to 0.73
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

### Building NN with 2 hidden layers, 600 neurons each and 600 epochs

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 600) # Stops much before 600 epochs

Epoch 1/600
15120/15120 [==============================] - 2s 128us/step - loss: 1.4482 - acc: 0.5579
Epoch 2/600
15120/15120 [==============================] - 1s 63us/step - loss: 0.8586 - acc: 0.6375
Epoch 3/600
15120/15120 [==============================] - 1s 65us/step - loss: 0.7648 - acc: 0.6808
Epoch 4/600
15120/15120 [==============================] - 1s 65us/step - loss: 0.7093 - acc: 0.7015
Epoch 5/600
15120/15120 [==============================] - 1s 87us/step - loss: 0.6712 - acc: 0.7181
Epoch 6/600
15120/15120 [==============================] - 1s 72us/step - loss: 0.6371 - acc: 0.7323
Epoch 7/600
15120/15120 [==============================] - 1s 60us/step - loss: 0.6131 - acc: 0.7477
Epoch 8/600
15120/15120 [==============================] - 1s 57us/step - loss: 0.5882 - acc: 0.7521
Epoch 9/600
15120/15120 [==============================] - 1s 53us/step - loss: 0.5748 - acc: 0.7563
Epoch 10/600
15120/15120 [==============================] - 1s 59us/step - loss: 0.5513 - 

In [17]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 2, 4, 4, 4, 4, 1, 1, 1, 4, 1, 1, 4, 4, 4, 2, 2, 1, 2, 4, 4,
       4, 4, 1, 1, 1, 1, 1, 1, 1, 2, 2, 4, 2, 2, 2, 1, 1, 1, 2, 2, 1, 4,
       4, 4, 4, 2, 1, 1, 1, 2, 2, 2, 2, 2, 4, 5, 5, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 4, 4, 2, 1, 1, 1, 2, 2, 2, 5, 5, 5,
       5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [18]:
forest_test['Cover_Type'] = pred_test   # Same kaggle score as model before above model 0.7594
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## Adding Dropout for Regularization

In [39]:
from keras.layers import Dropout

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dropout(p=0.1))
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dropout(p=0.1))
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 600)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  This is separate from the ipykernel package so we can avoid doing imports until
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  """


Epoch 1/600
15120/15120 [==============================] - 2s 144us/step - loss: 1.4896 - acc: 0.5396
Epoch 2/600
15120/15120 [==============================] - 1s 84us/step - loss: 0.8760 - acc: 0.6331
Epoch 3/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.7841 - acc: 0.6697
Epoch 4/600
15120/15120 [==============================] - 1s 84us/step - loss: 0.7329 - acc: 0.6922
Epoch 5/600
15120/15120 [==============================] - 1s 82us/step - loss: 0.6906 - acc: 0.7087
Epoch 6/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.6547 - acc: 0.7292
Epoch 7/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.6290 - acc: 0.7344
Epoch 8/600
15120/15120 [==============================] - 1s 81us/step - loss: 0.6115 - acc: 0.7451
Epoch 9/600
15120/15120 [==============================] - 1s 81us/step - loss: 0.5983 - acc: 0.7495
Epoch 10/600
15120/15120 [==============================] - 1s 84us/step - loss: 0.5743 - 

In [41]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 5, 5, 5,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2], dtype=int64)

## The Best score so far of all 3 algos - RF,XGBoost and NN

In [42]:
forest_test['Cover_Type'] = pred_test   # Kaggle score increased from 0.7594 to 0.7704
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## Increasing Dropout

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dropout(rate=0.2))
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dropout(rate=0.2))
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 600)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.2)`
  This is separate from the ipykernel package so we can avoid doing imports until
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.2)`
  """


Epoch 1/600
15120/15120 [==============================] - 2s 109us/step - loss: 1.4579 - acc: 0.5333
Epoch 2/600
15120/15120 [==============================] - 1s 82us/step - loss: 0.8761 - acc: 0.6333
Epoch 3/600
15120/15120 [==============================] - 1s 82us/step - loss: 0.7913 - acc: 0.6673
Epoch 4/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.7401 - acc: 0.6874
Epoch 5/600
15120/15120 [==============================] - 1s 81us/step - loss: 0.7000 - acc: 0.7049
Epoch 6/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.6726 - acc: 0.7177
Epoch 7/600
15120/15120 [==============================] - 1s 81us/step - loss: 0.6522 - acc: 0.7241
Epoch 8/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.6305 - acc: 0.7343
Epoch 9/600
15120/15120 [==============================] - 1s 81us/step - loss: 0.6035 - acc: 0.7444
Epoch 10/600
15120/15120 [==============================] - 1s 85us/step - loss: 0.5906 - 

In [44]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 5, 5, 5,
       5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [45]:
forest_test['Cover_Type'] = pred_test   # Kaggle score 0.7706, very little difference
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## RMS prop optimizer

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dropout(rate=0.2))
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dropout(rate=0.2))
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'RMSprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 600)

Epoch 1/600
15120/15120 [==============================] - 2s 104us/step - loss: 1.1798 - acc: 0.5589
Epoch 2/600
15120/15120 [==============================] - 1s 82us/step - loss: 0.8393 - acc: 0.6443
Epoch 3/600
15120/15120 [==============================] - 2s 106us/step - loss: 0.7811 - acc: 0.6706
Epoch 4/600
15120/15120 [==============================] - 1s 79us/step - loss: 0.7498 - acc: 0.6804
Epoch 5/600
15120/15120 [==============================] - 1s 80us/step - loss: 0.7109 - acc: 0.7014
Epoch 6/600
15120/15120 [==============================] - 1s 79us/step - loss: 0.6841 - acc: 0.7055
Epoch 7/600
15120/15120 [==============================] - 1s 79us/step - loss: 0.6619 - acc: 0.7187
Epoch 8/600
15120/15120 [==============================] - 1s 81us/step - loss: 0.6545 - acc: 0.7226
Epoch 9/600
15120/15120 [==============================] - 1s 80us/step - loss: 0.6272 - acc: 0.7372
Epoch 10/600
15120/15120 [==============================] - 1s 83us/step - loss: 0.6125 -

In [47]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 5, 5, 5,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1], dtype=int64)

In [48]:
forest_test['Cover_Type'] = pred_test   # Kaggle score reduced to 0.7651 with RMSprop optimizer from 0.77 
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

## SGD optimzer

In [ ]:
classifier6 = Sequential()
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform',input_dim = 54))#First Hidden Layer
classifier6.add(Dropout(rate=0.2))
classifier6.add(Dense(units = 600,activation = 'relu',kernel_initializer = 'uniform')) #2nd hidden layer
classifier6.add(Dropout(rate=0.2))
classifier6.add(Dense(units = 8,activation = 'softmax',kernel_initializer = 'uniform'))
classifier6.compile(optimizer = 'SGD', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier6.fit(data_train, categorical_covertype_train, batch_size = 1000, epochs = 600)

Epoch 1/600
15120/15120 [==============================] - 2s 105us/step - loss: 2.0730 - acc: 0.1684
Epoch 2/600
15120/15120 [==============================] - 1s 77us/step - loss: 2.0543 - acc: 0.2229
Epoch 3/600
15120/15120 [==============================] - 1s 77us/step - loss: 2.0376 - acc: 0.2741
Epoch 4/600
15120/15120 [==============================] - 1s 76us/step - loss: 2.0208 - acc: 0.3192
Epoch 5/600
15120/15120 [==============================] - 1s 76us/step - loss: 2.0043 - acc: 0.3573
Epoch 6/600
15120/15120 [==============================] - 1s 78us/step - loss: 1.9885 - acc: 0.3805
Epoch 7/600
15120/15120 [==============================] - 1s 77us/step - loss: 1.9720 - acc: 0.4097
Epoch 8/600
15120/15120 [==============================] - 1s 78us/step - loss: 1.9556 - acc: 0.4299
Epoch 9/600
15120/15120 [==============================] - 1s 77us/step - loss: 1.9385 - acc: 0.4456
Epoch 10/600
15120/15120 [==============================] - 1s 77us/step - loss: 1.9219 - 

In [50]:
pred_test = classifier6.predict_classes(data_test) # predict gives prob even though softmax classifier is used
pred_test[0:100]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [51]:
forest_test['Cover_Type'] = pred_test   # Kaggle score reduced to 0.62 
forest_test[['Id','Cover_Type']].to_csv("ForestCover_ANN_model.csv",index = False)

#### Best optimzer in this case - Adam. SGD with default parameters gave poor accuracy